AWSTemplateFormatVersion: 2010-09-09
Description: "for production/test and public/private"
Parameters:
  Instancetype:
    Type : String 
    Description: "dess"
    Default: t2.micro
  Env:
    Description: "Deployment Environment"
    Type : String 
    Default: "Test"
    AllowedValues:
      - Test
      - Prod
  NetMode:
    Description: "public or private"
    Type: String
    Default: "Private"
    AllowedValues:
      - Public
      - Private
  AMID:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>"
    Default: "/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2"
  Message:
    Description: "Message for HTML page"
    Default: "Test1"
    Type: "String"
Conditions:
  IsProduction: !Equals 
    - !Ref Env
    - Prod
  IsTest : !Equals 
    - !Ref Env
    - Test
  IsPublic: !Equals
    - !Ref NetMode
    - Public
  IsPrivate: !Equals
    - !Ref NetMode
    - Private
Resources:
#VPC Endpoints For SSM and cloudformation
#SSM VPC Endpoint
  ssmVPCe:
    Type: AWS::EC2::VPCEndpoint
    Condition: IsPrivate
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !ImportValue  PriSub1  
      SecurityGroupIds:
        - !ImportValue HTTPS
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      VpcId: !ImportValue  VPCID
#AGent to SSM VPCEndpoint
  ssmec2messagesVPCe:
    Type: AWS::EC2::VPCEndpoint
    Condition: IsPrivate
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !ImportValue  PriSub1  
      SecurityGroupIds:
        - !ImportValue HTTPS
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ec2messages
      VpcId: !ImportValue  VPCID
  #Session Manager VPC Endpoint
  ssmmessagesVPCe:
    Type: AWS::EC2::VPCEndpoint
    Condition: IsPrivate
    Properties:
      VpcEndpointType: "Interface"
      PrivateDnsEnabled: "True"
      SubnetIds:
        - !ImportValue  PriSub1  
      SecurityGroupIds:
        - !ImportValue HTTPS
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssmmessages
      VpcId: !ImportValue  VPCID
#Cloudformation endpoint for resource signal (creation policy)
  CFNVPCInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: IsPrivate
    Properties:
      VpcEndpointType: Interface
      PrivateDnsEnabled: true
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.cloudformation'
      VpcId: !ImportValue VPCID
      SubnetIds:
        - !ImportValue  PriSub1  
      SecurityGroupIds:
        - !ImportValue HTTPS
#S3 GW VPC Endpoint For PatchBaseLineFiles , any custom resources/waitconditionurl will use it too
  s3VPCe:
    Condition: IsPrivate 
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - !ImportValue  PrivateRT

      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      VpcId: !ImportValue VPCID
#private instance

  PrivateInstance:
    Type: AWS::EC2::Instance
    Condition: IsPrivate
    DependsOn:
      - CFNVPCInterfaceEndpoint
      - ssmVPCe
      - ssmmessagesVPCe
      - ssmec2messagesVPCe
      - s3VPCe
    Metadata:
      'AWS::CloudFormation::Init':
        configSets: 
          default: 
            - "seting-cfhup"
        seting-cfhup:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
                verbose=true
              mode: '000400'
              owner: 'root'
              group: 'root'
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.PrivateInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource PrivateInstance --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: 'root'
              group: 'root'
          commands:
            requiredonly:
              command: "/bin/echo -n "
          services:
            sysvinit:
              cfn-hup:
                enabled: "true"
                ensureRunning: "true"
                files:
                  - /etc/cfn/cfn-hup.conf
                  - /etc/cfn/hooks.d/cfn-auto-reloader.conf               
    CreationPolicy:
      ResourceSignal:
        Count: 1
        Timeout: PT40M    
    Properties:
      InstanceType: !Ref Instancetype
      ImageId: !Ref AMID
      IamInstanceProfile: !ImportValue EC2InsPro

      SecurityGroupIds: !
        - !ImportValue  None
      SubnetId: !ImportValue  PriSub1      
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource   PrivateInstance --region ${AWS::Region}
          /opt/aws/bin/cfn-signal -e $? --region ${AWS::Region} --stack ${AWS::StackName} --resource   PrivateInstance