name: modify-cloudformation-init-with-newtag-url

on:
  push:
    tags:        
      - '*-prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Debug
      run: echo "${GITHUB_REF##*/}"
