name: modify-cloudformation-init-with-newtag-url2

on:
  push:
    tags:        
      - '*-prod'

jobs:
  update-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-region: us-east-1
          role-to-assume: ${{ AWS_ROLE }}
          role-session-name: OIDCSession
    - name: modify-template-for-cfn-init
      run: |
        echo "the trigger tag is ${GITHUB_REF##*/}"
        wget https://raw.githubusercontent.com/yasser-alhawary/cloudformation/master/testing.yaml --output-document=/tmp/template.yaml
        sed 's/tarball.*$/tarball\/'"${GITHUB_REF##*\/}"'/gi' /tmp/template.yaml   
        cat /tmp/template.yaml  
        aws cloudformation update-stack --template-body file:///tmp/template.yaml --stack-name gh
