name: modify-cloudformation-init-with-newtag-url2

on:
  push:
    tags:        
      - '*-prod'
permissions:
  id-token: write
jobs:
  update-stack:
    runs-on: ubuntu-latest
    steps:
    - name: modify-template-for-cfn-init
      run: |
        echo "the trigger tag is ${GITHUB_REF##*/}"
        wget https://raw.githubusercontent.com/yasser-alhawary/AWS-Configurations/master/CloudFormation-Templates/testing.yaml --output-document=/tmp/template.yaml
        sed -i 's/tarball.*$/tarball\/'"${GITHUB_REF##*\/}"'/gi' /tmp/template.yaml   
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: OIDCSession2
    - run: aws cloudformation update-stack --template-body file:///tmp/template.yaml --stack-name gh
      shell: bash
