name: modify-cloudformation-init-with-newtag-url2

on:
  push:
    tags:        
      - '*-prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: testing
      run: |
        echo "the trigger tag is ${GITHUB_REF##*/}"
        wget https://raw.githubusercontent.com/yasser-alhawary/cloudformation/master/testing.yaml --output-document=/tmp/template.yaml
        cat /tmp/template.yaml
        sed 's/tarball.*\"$/tarball\/'"${GITHUB_REF##*\/}"'/gi' /tmp/template.yaml   
        cat /tmp/template.yaml  
